image:
    - Visual Studio 2017
environment: 
  matrix: 
    - platform: "Visual Studio 15 2017 Win64"
    - platform: "Visual Studio 15 2017 ARM"
before_build:
    - ps : mkdir build_appveyor
    - ps : cd build_appveyor
build_script:
    - cmake .. -G "%platform%"
    - cmake --build ./